/**
 * Trusted source registry — Phase 2 expansion.
 *
 * Only `active: true` + HTTPS `feedUrl` sources are fetched live.
 * Unavailable / licensed / paywalled sources stay documented with active:false.
 * Do not scrape, bypass paywalls, or invent endpoints.
 */

import { SOURCE_TIERS } from "./sourceTiers.mjs";

/**
 * @typedef {object} SourceEntry
 * @property {string} id
 * @property {string} name
 * @property {string} organization
 * @property {string} domain
 * @property {"rss"|"json"|"official"|"manual"|"blocked"} type
 * @property {string[]} scope
 * @property {string[]} topics
 * @property {string} coverageType
 * @property {string} geography
 * @property {string} homepage
 * @property {string|null} feedUrl
 * @property {string} authorityTier
 * @property {boolean} requiresSecondaryConfirmation
 * @property {boolean} active
 * @property {boolean} supportsDiscovery
 * @property {boolean} supportsCorroboration
 * @property {"primary"|"secondary"|"discovery"|"blocked"} role
 * @property {string} updateFrequency
 * @property {string} licensingNotes
 * @property {string} notes
 */

/** @type {SourceEntry[]} */
export const SOURCE_REGISTRY = [
    // ── Active primary / official ───────────────────────────────────────────
    {
        id: "nist-news",
        name: "NIST News",
        organization: "National Institute of Standards and Technology",
        domain: "nist.gov",
        type: "rss",
        scope: ["national"],
        topics: ["ai", "cybersecurity", "standards", "semiconductors", "science"],
        coverageType: "official-news",
        geography: "US",
        homepage: "https://www.nist.gov/news-events/news",
        feedUrl: "https://www.nist.gov/news-events/news/rss.xml",
        authorityTier: SOURCE_TIERS.TIER_1_PRIMARY,
        requiresSecondaryConfirmation: false,
        active: true,
        supportsDiscovery: true,
        supportsCorroboration: true,
        role: "primary",
        updateFrequency: "several/week",
        licensingNotes: "U.S. government work; attribute NIST.",
        notes: "Official NIST news feed.",
    },
    {
        id: "cisa-advisories",
        name: "CISA Cybersecurity Advisories",
        organization: "Cybersecurity and Infrastructure Security Agency",
        domain: "cisa.gov",
        type: "rss",
        scope: ["national"],
        topics: ["cybersecurity", "infrastructure", "software"],
        coverageType: "official-advisory",
        geography: "US",
        homepage: "https://www.cisa.gov/news-events/cybersecurity-advisories",
        feedUrl: "https://www.cisa.gov/cybersecurity-advisories/all.xml",
        authorityTier: SOURCE_TIERS.TIER_1_PRIMARY,
        requiresSecondaryConfirmation: false,
        active: true,
        supportsDiscovery: true,
        supportsCorroboration: true,
        role: "primary",
        updateFrequency: "daily",
        licensingNotes: "U.S. government work; attribute CISA.",
        notes: "Official CISA advisory feed. High volume of ICS product advisories can skew selection when secondary news volume is low.",
    },
    {
        id: "nasa-press",
        name: "NASA Press Releases",
        organization: "National Aeronautics and Space Administration",
        domain: "nasa.gov",
        type: "rss",
        scope: ["national", "international"],
        topics: ["science", "space", "technology"],
        coverageType: "official-press",
        geography: "US / international",
        homepage: "https://www.nasa.gov/news-release/",
        feedUrl: "https://www.nasa.gov/rss/dyn/breaking_news.rss",
        authorityTier: SOURCE_TIERS.TIER_1_PRIMARY,
        requiresSecondaryConfirmation: false,
        active: true,
        supportsDiscovery: true,
        supportsCorroboration: true,
        role: "primary",
        updateFrequency: "daily",
        licensingNotes: "U.S. government work; attribute NASA.",
        notes: "Official NASA breaking-news RSS.",
    },
    {
        id: "sec-press",
        name: "SEC Press Releases",
        organization: "U.S. Securities and Exchange Commission",
        domain: "sec.gov",
        type: "rss",
        scope: ["national"],
        topics: ["finance", "regulation", "business", "technology"],
        coverageType: "official-press",
        geography: "US",
        homepage: "https://www.sec.gov/newsroom/press-releases",
        feedUrl: "https://www.sec.gov/news/pressreleases.rss",
        authorityTier: SOURCE_TIERS.TIER_1_PRIMARY,
        requiresSecondaryConfirmation: false,
        active: true,
        supportsDiscovery: true,
        supportsCorroboration: true,
        role: "primary",
        updateFrequency: "several/week",
        licensingNotes: "U.S. government work; identify user-agent per SEC policy.",
        notes: "Official SEC press-release feed.",
    },
    {
        id: "federal-reserve-press",
        name: "Federal Reserve Press",
        organization: "Board of Governors of the Federal Reserve System",
        domain: "federalreserve.gov",
        type: "rss",
        scope: ["national", "international"],
        topics: ["finance", "business", "regulation", "economy"],
        coverageType: "official-press",
        geography: "US",
        homepage: "https://www.federalreserve.gov/newsevents.htm",
        feedUrl: "https://www.federalreserve.gov/feeds/press_all.xml",
        authorityTier: SOURCE_TIERS.TIER_1_PRIMARY,
        requiresSecondaryConfirmation: false,
        active: true,
        supportsDiscovery: true,
        supportsCorroboration: true,
        role: "primary",
        updateFrequency: "several/week",
        licensingNotes: "U.S. government work; attribute Federal Reserve.",
        notes: "Official Fed press feed — finance/macro diversity.",
    },
    {
        id: "ftc-press",
        name: "FTC Press Releases",
        organization: "Federal Trade Commission",
        domain: "ftc.gov",
        type: "rss",
        scope: ["national"],
        topics: ["consumer tech", "policy", "regulation", "privacy", "business"],
        coverageType: "official-press",
        geography: "US",
        homepage: "https://www.ftc.gov/news-events",
        feedUrl: "https://www.ftc.gov/feeds/press-release.xml",
        authorityTier: SOURCE_TIERS.TIER_1_PRIMARY,
        requiresSecondaryConfirmation: false,
        active: true,
        supportsDiscovery: true,
        supportsCorroboration: true,
        role: "primary",
        updateFrequency: "several/week",
        licensingNotes: "U.S. government work; attribute FTC.",
        notes: "Verified FTC press-release RSS (previously inactive pending endpoint).",
    },
    {
        id: "fda-press",
        name: "FDA Press Releases",
        organization: "U.S. Food and Drug Administration",
        domain: "fda.gov",
        type: "rss",
        scope: ["national"],
        topics: ["health", "regulation", "science", "technology"],
        coverageType: "official-press",
        geography: "US",
        homepage: "https://www.fda.gov/news-events/fda-newsroom/press-announcements",
        feedUrl: "https://www.fda.gov/about-fda/contact-fda/stay-informed/rss-feeds/press-releases/rss.xml",
        authorityTier: SOURCE_TIERS.TIER_1_PRIMARY,
        requiresSecondaryConfirmation: false,
        active: true,
        supportsDiscovery: true,
        supportsCorroboration: true,
        role: "primary",
        updateFrequency: "several/week",
        licensingNotes: "U.S. government work; attribute FDA.",
        notes: "Official FDA press RSS — health/regulation desk.",
    },
    {
        id: "cdc-mmwr",
        name: "CDC Media / MMWR-related RSS",
        organization: "Centers for Disease Control and Prevention",
        domain: "cdc.gov",
        type: "rss",
        scope: ["national", "international"],
        topics: ["health", "science", "environment"],
        coverageType: "official-media",
        geography: "US",
        homepage: "https://www.cdc.gov/",
        feedUrl: "https://tools.cdc.gov/api/v2/resources/media/132092.rss",
        authorityTier: SOURCE_TIERS.TIER_1_PRIMARY,
        requiresSecondaryConfirmation: false,
        active: true,
        supportsDiscovery: true,
        supportsCorroboration: true,
        role: "primary",
        updateFrequency: "weekly+",
        licensingNotes: "U.S. government work; attribute CDC.",
        notes: "CDC media RSS endpoint verified reachable; treat as health primary.",
    },
    {
        id: "noaa-news",
        name: "NOAA News",
        organization: "National Oceanic and Atmospheric Administration",
        domain: "noaa.gov",
        type: "rss",
        scope: ["national", "international"],
        topics: ["environment", "science", "climate"],
        coverageType: "official-news",
        geography: "US",
        homepage: "https://www.noaa.gov/",
        feedUrl: "https://www.noaa.gov/rss.xml",
        authorityTier: SOURCE_TIERS.TIER_1_PRIMARY,
        requiresSecondaryConfirmation: false,
        active: true,
        supportsDiscovery: true,
        supportsCorroboration: true,
        role: "primary",
        updateFrequency: "several/week",
        licensingNotes: "U.S. government work; attribute NOAA.",
        notes: "Official NOAA RSS — environment/climate desk.",
    },
    {
        id: "nsf-news",
        name: "NSF News",
        organization: "National Science Foundation",
        domain: "nsf.gov",
        type: "rss",
        scope: ["national"],
        topics: ["science", "ai", "education", "research", "technology"],
        coverageType: "official-news",
        geography: "US",
        homepage: "https://www.nsf.gov/news",
        feedUrl: "https://www.nsf.gov/rss/rss_www_news.xml",
        authorityTier: SOURCE_TIERS.TIER_1_PRIMARY,
        requiresSecondaryConfirmation: false,
        active: true,
        supportsDiscovery: true,
        supportsCorroboration: true,
        role: "primary",
        updateFrequency: "several/week",
        licensingNotes: "U.S. government work; attribute NSF.",
        notes: "Verified NSF RSS endpoint.",
    },

    // ── Active company primary (require independent secondary) ──────────────
    {
        id: "openai-blog",
        name: "OpenAI Blog",
        organization: "OpenAI",
        domain: "openai.com",
        type: "rss",
        scope: ["national", "international"],
        topics: ["ai", "technology", "software"],
        coverageType: "company-newsroom",
        geography: "US / international",
        homepage: "https://openai.com/blog",
        feedUrl: "https://openai.com/blog/rss.xml",
        authorityTier: SOURCE_TIERS.TIER_1_PRIMARY,
        requiresSecondaryConfirmation: true,
        active: true,
        supportsDiscovery: true,
        supportsCorroboration: true,
        role: "primary",
        updateFrequency: "irregular",
        licensingNotes: "Company blog; attribute OpenAI; claims are company statements.",
        notes: "Company primary — needs independent news/specialty corroboration for READY.",
    },
    {
        id: "nvidia-blog",
        name: "NVIDIA Blog",
        organization: "NVIDIA",
        domain: "nvidia.com",
        type: "rss",
        scope: ["national", "international"],
        topics: ["ai", "semiconductors", "technology", "business"],
        coverageType: "company-newsroom",
        geography: "US / international",
        homepage: "https://blogs.nvidia.com/",
        feedUrl: "https://blogs.nvidia.com/feed/",
        authorityTier: SOURCE_TIERS.TIER_1_PRIMARY,
        requiresSecondaryConfirmation: true,
        active: true,
        supportsDiscovery: true,
        supportsCorroboration: true,
        role: "primary",
        updateFrequency: "several/week",
        licensingNotes: "Company blog; attribute NVIDIA.",
        notes: "Company primary — requires secondary confirmation.",
    },
    {
        id: "google-ai-blog",
        name: "Google Blog — AI",
        organization: "Google",
        domain: "blog.google",
        type: "rss",
        scope: ["national", "international"],
        topics: ["ai", "technology", "software"],
        coverageType: "company-newsroom",
        geography: "US / international",
        homepage: "https://blog.google/technology/ai/",
        feedUrl: "https://blog.google/technology/ai/rss/",
        authorityTier: SOURCE_TIERS.TIER_1_PRIMARY,
        requiresSecondaryConfirmation: true,
        active: true,
        supportsDiscovery: true,
        supportsCorroboration: true,
        role: "primary",
        updateFrequency: "several/week",
        licensingNotes: "Company blog; attribute Google.",
        notes: "Company primary — requires secondary confirmation.",
    },
    {
        id: "deepmind-blog",
        name: "Google DeepMind Blog",
        organization: "Google DeepMind",
        domain: "deepmind.google",
        type: "rss",
        scope: ["international"],
        topics: ["ai", "science", "research", "technology"],
        coverageType: "company-research",
        geography: "international",
        homepage: "https://deepmind.google/blog/",
        feedUrl: "https://deepmind.google/blog/rss.xml",
        authorityTier: SOURCE_TIERS.TIER_1_PRIMARY,
        requiresSecondaryConfirmation: true,
        active: true,
        supportsDiscovery: true,
        supportsCorroboration: true,
        role: "primary",
        updateFrequency: "irregular",
        licensingNotes: "Company research blog; attribute Google DeepMind.",
        notes: "Company primary — requires secondary confirmation.",
    },
    {
        id: "microsoft-research",
        name: "Microsoft Research",
        organization: "Microsoft",
        domain: "microsoft.com",
        type: "rss",
        scope: ["national", "international"],
        topics: ["ai", "technology", "research", "software"],
        coverageType: "company-research",
        geography: "US / international",
        homepage: "https://www.microsoft.com/en-us/research/",
        feedUrl: "https://www.microsoft.com/en-us/research/feed/",
        authorityTier: SOURCE_TIERS.TIER_1_PRIMARY,
        requiresSecondaryConfirmation: true,
        active: true,
        supportsDiscovery: true,
        supportsCorroboration: true,
        role: "primary",
        updateFrequency: "several/week",
        licensingNotes: "Company research feed; attribute Microsoft. Main MSFT blog feed unavailable (410/closed).",
        notes: "Reachable research feed substitute; corporate newsroom blog feed not usable.",
    },
    {
        id: "meta-newsroom",
        name: "Meta Newsroom",
        organization: "Meta",
        domain: "about.fb.com",
        type: "rss",
        scope: ["national", "international"],
        topics: ["ai", "technology", "business", "policy"],
        coverageType: "company-newsroom",
        geography: "US / international",
        homepage: "https://about.fb.com/news/",
        feedUrl: "https://about.fb.com/news/feed/",
        authorityTier: SOURCE_TIERS.TIER_1_PRIMARY,
        requiresSecondaryConfirmation: true,
        active: true,
        supportsDiscovery: true,
        supportsCorroboration: true,
        role: "primary",
        updateFrequency: "several/week",
        licensingNotes: "Company newsroom; attribute Meta.",
        notes: "Company primary — requires secondary confirmation.",
    },
    {
        id: "apple-newsroom",
        name: "Apple Newsroom",
        organization: "Apple",
        domain: "apple.com",
        type: "rss",
        scope: ["national", "international"],
        topics: ["technology", "business", "hardware", "ai"],
        coverageType: "company-newsroom",
        geography: "US / international",
        homepage: "https://www.apple.com/newsroom/",
        feedUrl: "https://www.apple.com/newsroom/rss-feed.rss",
        authorityTier: SOURCE_TIERS.TIER_1_PRIMARY,
        requiresSecondaryConfirmation: true,
        active: true,
        supportsDiscovery: true,
        supportsCorroboration: true,
        role: "primary",
        updateFrequency: "irregular",
        licensingNotes: "Company newsroom; attribute Apple.",
        notes: "Company primary — requires secondary confirmation.",
    },
    {
        id: "aws-blog",
        name: "AWS News Blog",
        organization: "Amazon Web Services",
        domain: "aws.amazon.com",
        type: "rss",
        scope: ["national", "international"],
        topics: ["technology", "cloud", "ai", "business"],
        coverageType: "company-newsroom",
        geography: "US / international",
        homepage: "https://aws.amazon.com/blogs/aws/",
        feedUrl: "https://aws.amazon.com/blogs/aws/feed/",
        authorityTier: SOURCE_TIERS.TIER_1_PRIMARY,
        requiresSecondaryConfirmation: true,
        active: true,
        supportsDiscovery: true,
        supportsCorroboration: true,
        role: "primary",
        updateFrequency: "several/week",
        licensingNotes: "Company blog; attribute AWS/Amazon.",
        notes: "Company primary — requires secondary confirmation.",
    },

    // ── Active Tier-1 newsrooms ─────────────────────────────────────────────
    {
        id: "bbc-technology",
        name: "BBC News Technology",
        organization: "BBC",
        domain: "bbc.co.uk",
        type: "rss",
        scope: ["international", "national"],
        topics: ["technology", "ai", "science", "business"],
        coverageType: "newsroom",
        geography: "UK / international",
        homepage: "https://www.bbc.com/news/technology",
        feedUrl: "https://feeds.bbci.co.uk/news/technology/rss.xml",
        authorityTier: SOURCE_TIERS.TIER_1_NEWS,
        requiresSecondaryConfirmation: true,
        active: true,
        supportsDiscovery: true,
        supportsCorroboration: true,
        role: "secondary",
        updateFrequency: "daily",
        licensingNotes: "Public RSS; attribute BBC; respect BBC terms — no paywall bypass.",
        notes: "High-authority newsroom technology desk.",
    },
    {
        id: "npr-technology",
        name: "NPR Technology",
        organization: "National Public Radio",
        domain: "npr.org",
        type: "rss",
        scope: ["national", "international"],
        topics: ["technology", "ai", "science", "business", "health"],
        coverageType: "newsroom",
        geography: "US",
        homepage: "https://www.npr.org/sections/technology/",
        feedUrl: "https://feeds.npr.org/1019/rss.xml",
        authorityTier: SOURCE_TIERS.TIER_1_NEWS,
        requiresSecondaryConfirmation: true,
        active: true,
        supportsDiscovery: true,
        supportsCorroboration: true,
        role: "secondary",
        updateFrequency: "daily",
        licensingNotes: "Public RSS; attribute NPR.",
        notes: "High-authority U.S. public newsroom technology section.",
    },

    // ── Active Tier-2 specialty ─────────────────────────────────────────────
    {
        id: "the-verge",
        name: "The Verge",
        organization: "Vox Media / The Verge",
        domain: "theverge.com",
        type: "rss",
        scope: ["national", "international"],
        topics: ["technology", "ai", "business", "software"],
        coverageType: "specialty-news",
        geography: "US / international",
        homepage: "https://www.theverge.com/",
        feedUrl: "https://www.theverge.com/rss/index.xml",
        authorityTier: SOURCE_TIERS.TIER_2_REPUTABLE,
        requiresSecondaryConfirmation: true,
        active: true,
        supportsDiscovery: true,
        supportsCorroboration: true,
        role: "secondary",
        updateFrequency: "daily",
        licensingNotes: "Public RSS; attribute The Verge; respect site terms.",
        notes: "Established specialty technology publication.",
    },
    {
        id: "techcrunch",
        name: "TechCrunch",
        organization: "TechCrunch / Yahoo",
        domain: "techcrunch.com",
        type: "rss",
        scope: ["national", "international"],
        topics: ["technology", "ai", "business", "startups", "finance"],
        coverageType: "specialty-news",
        geography: "US / international",
        homepage: "https://techcrunch.com/",
        feedUrl: "https://techcrunch.com/feed/",
        authorityTier: SOURCE_TIERS.TIER_2_REPUTABLE,
        requiresSecondaryConfirmation: true,
        active: true,
        supportsDiscovery: true,
        supportsCorroboration: true,
        role: "secondary",
        updateFrequency: "daily",
        licensingNotes: "Public RSS; attribute TechCrunch.",
        notes: "Startup/business technology specialty.",
    },
    {
        id: "ars-technica",
        name: "Ars Technica",
        organization: "Condé Nast / Ars Technica",
        domain: "arstechnica.com",
        type: "rss",
        scope: ["national", "international"],
        topics: ["technology", "science", "ai", "cybersecurity", "space"],
        coverageType: "specialty-news",
        geography: "US / international",
        homepage: "https://arstechnica.com/",
        feedUrl: "https://feeds.arstechnica.com/arstechnica/index",
        authorityTier: SOURCE_TIERS.TIER_2_REPUTABLE,
        requiresSecondaryConfirmation: true,
        active: true,
        supportsDiscovery: true,
        supportsCorroboration: true,
        role: "secondary",
        updateFrequency: "daily",
        licensingNotes: "Public RSS; attribute Ars Technica.",
        notes: "Strong science/tech specialty newsroom.",
    },
    {
        id: "ieee-spectrum",
        name: "IEEE Spectrum",
        organization: "IEEE",
        domain: "spectrum.ieee.org",
        type: "rss",
        scope: ["international"],
        topics: ["technology", "science", "ai", "semiconductors", "engineering"],
        coverageType: "specialty-news",
        geography: "international",
        homepage: "https://spectrum.ieee.org/",
        feedUrl: "https://spectrum.ieee.org/feeds/feed.rss",
        authorityTier: SOURCE_TIERS.TIER_2_REPUTABLE,
        requiresSecondaryConfirmation: true,
        active: true,
        supportsDiscovery: true,
        supportsCorroboration: true,
        role: "secondary",
        updateFrequency: "several/week",
        licensingNotes: "Public RSS; attribute IEEE Spectrum.",
        notes: "Engineering/technology specialty.",
    },
    {
        id: "mit-technology-review",
        name: "MIT Technology Review",
        organization: "MIT Technology Review",
        domain: "technologyreview.com",
        type: "rss",
        scope: ["national", "international"],
        topics: ["ai", "technology", "science", "business"],
        coverageType: "specialty-news",
        geography: "US / international",
        homepage: "https://www.technologyreview.com/",
        feedUrl: "https://www.technologyreview.com/feed/",
        authorityTier: SOURCE_TIERS.TIER_2_REPUTABLE,
        requiresSecondaryConfirmation: true,
        active: true,
        supportsDiscovery: true,
        supportsCorroboration: true,
        role: "secondary",
        updateFrequency: "several/week",
        licensingNotes: "Public RSS; attribute MIT Technology Review; some articles may be paywalled — feed metadata only.",
        notes: "Specialty AI/tech analysis; do not scrape paywalled bodies.",
    },
    {
        id: "nature-news",
        name: "Nature (journal RSS)",
        organization: "Springer Nature",
        domain: "nature.com",
        type: "rss",
        scope: ["international"],
        topics: ["science", "health", "environment", "ai"],
        coverageType: "journal",
        geography: "international",
        homepage: "https://www.nature.com/",
        feedUrl: "https://www.nature.com/nature.rss",
        authorityTier: SOURCE_TIERS.TIER_2_REPUTABLE,
        requiresSecondaryConfirmation: true,
        active: true,
        supportsDiscovery: true,
        supportsCorroboration: true,
        role: "secondary",
        updateFrequency: "weekly+",
        licensingNotes: "Public journal RSS metadata; fulltext may be paywalled — do not scrape.",
        notes: "Science journal feed for discovery/corroboration of research announcements.",
    },
    {
        id: "mit-ai",
        name: "MIT News: Artificial Intelligence",
        organization: "Massachusetts Institute of Technology",
        domain: "news.mit.edu",
        type: "rss",
        scope: ["national", "international"],
        topics: ["ai", "research", "education", "technology"],
        coverageType: "university-news",
        geography: "US / international",
        homepage: "https://news.mit.edu/topic/artificial-intelligence2",
        feedUrl: "https://news.mit.edu/rss/topic/artificial-intelligence2",
        authorityTier: SOURCE_TIERS.TIER_2_REPUTABLE,
        requiresSecondaryConfirmation: true,
        active: true,
        supportsDiscovery: true,
        supportsCorroboration: true,
        role: "secondary",
        updateFrequency: "several/week",
        licensingNotes: "University news; attribute MIT News.",
        notes: "MIT News topical AI feed; corroborate external claims.",
    },

    // ── Phase 4 complementary primaries / secondaries ───────────────────────
    {
        id: "epa-news",
        name: "EPA News Releases",
        organization: "U.S. Environmental Protection Agency",
        domain: "epa.gov",
        type: "rss",
        scope: ["national"],
        topics: ["environment", "science", "health", "policy"],
        coverageType: "official-press",
        geography: "US",
        homepage: "https://www.epa.gov/newsreleases",
        feedUrl: "https://www.epa.gov/newsreleases/search/rss",
        authorityTier: SOURCE_TIERS.TIER_1_PRIMARY,
        requiresSecondaryConfirmation: false,
        active: true,
        supportsDiscovery: true,
        supportsCorroboration: true,
        role: "primary",
        updateFrequency: "several/week",
        licensingNotes: "U.S. government work; attribute EPA.",
        notes: "Phase 4: fills environment desk primary gap for Blog + News pairing.",
    },
    {
        id: "usgs-news",
        name: "USGS News",
        organization: "U.S. Geological Survey",
        domain: "usgs.gov",
        type: "rss",
        scope: ["national"],
        topics: ["science", "environment", "space", "technology"],
        coverageType: "official-news",
        geography: "US",
        homepage: "https://www.usgs.gov/news",
        feedUrl: "https://www.usgs.gov/news/news-releases/feed",
        authorityTier: SOURCE_TIERS.TIER_1_PRIMARY,
        requiresSecondaryConfirmation: false,
        active: true,
        supportsDiscovery: true,
        supportsCorroboration: true,
        role: "primary",
        updateFrequency: "several/week",
        licensingNotes: "U.S. government work; attribute USGS.",
        notes: "Phase 4: science/environment primary complement to NOAA/NASA.",
    },
    {
        id: "energy-gov-news",
        name: "U.S. Department of Energy News",
        organization: "U.S. Department of Energy",
        domain: "energy.gov",
        type: "rss",
        scope: ["national"],
        topics: ["energy", "science", "technology", "infrastructure", "ai"],
        coverageType: "official-press",
        geography: "US",
        homepage: "https://www.energy.gov/news",
        feedUrl: "https://www.energy.gov/rss/press-releases.xml",
        authorityTier: SOURCE_TIERS.TIER_1_PRIMARY,
        requiresSecondaryConfirmation: false,
        active: true,
        supportsDiscovery: true,
        supportsCorroboration: true,
        role: "primary",
        updateFrequency: "several/week",
        licensingNotes: "U.S. government work; attribute DOE.",
        notes: "Phase 4: energy/infrastructure primary for AI data-center adjacent coverage.",
    },
    {
        id: "esa-news",
        name: "ESA Space News",
        organization: "European Space Agency",
        domain: "esa.int",
        type: "rss",
        scope: ["international"],
        topics: ["space", "science", "technology"],
        coverageType: "official-news",
        geography: "EU / international",
        homepage: "https://www.esa.int/",
        feedUrl: "https://www.esa.int/rssfeed/Our_Activities/Space_Science",
        authorityTier: SOURCE_TIERS.TIER_1_PRIMARY,
        requiresSecondaryConfirmation: false,
        active: true,
        supportsDiscovery: true,
        supportsCorroboration: true,
        role: "primary",
        updateFrequency: "several/week",
        licensingNotes: "ESA content; attribute ESA; check item-level reuse terms.",
        notes: "Phase 4: international space primary to pair with NASA / Ars / Nature.",
    },
    {
        id: "guardian-technology",
        name: "The Guardian Technology",
        organization: "Guardian News & Media",
        domain: "theguardian.com",
        type: "rss",
        scope: ["international", "national"],
        topics: ["technology", "ai", "business", "science", "environment"],
        coverageType: "newsroom",
        geography: "UK / international",
        homepage: "https://www.theguardian.com/technology",
        feedUrl: "https://www.theguardian.com/uk/technology/rss",
        authorityTier: SOURCE_TIERS.TIER_1_NEWS,
        requiresSecondaryConfirmation: true,
        active: true,
        supportsDiscovery: true,
        supportsCorroboration: true,
        role: "secondary",
        updateFrequency: "daily",
        licensingNotes: "Public RSS; attribute The Guardian; respect robots and terms.",
        notes: "Phase 4: independent international newsroom to improve READY pairing potential.",
    },
    {
        id: "cloudflare-blog",
        name: "Cloudflare Blog",
        organization: "Cloudflare",
        domain: "cloudflare.com",
        type: "rss",
        scope: ["international", "national"],
        topics: ["cybersecurity", "technology", "software", "infrastructure"],
        coverageType: "company-blog",
        geography: "international",
        homepage: "https://blog.cloudflare.com/",
        feedUrl: "https://blog.cloudflare.com/rss/",
        authorityTier: SOURCE_TIERS.TIER_1_PRIMARY,
        requiresSecondaryConfirmation: true,
        active: true,
        supportsDiscovery: true,
        supportsCorroboration: true,
        role: "primary",
        updateFrequency: "several/week",
        licensingNotes: "Company blog; attribute Cloudflare; requires independent secondary for READY.",
        notes: "Phase 4: cybersecurity/infrastructure company primary (secondary confirmation required).",
    },
    {
        id: "huggingface-blog",
        name: "Hugging Face Blog",
        organization: "Hugging Face",
        domain: "huggingface.co",
        type: "rss",
        scope: ["international"],
        topics: ["ai", "software", "research", "technology"],
        coverageType: "company-blog",
        geography: "international",
        homepage: "https://huggingface.co/blog",
        feedUrl: "https://huggingface.co/blog/feed.xml",
        authorityTier: SOURCE_TIERS.TIER_2_REPUTABLE,
        requiresSecondaryConfirmation: true,
        active: true,
        supportsDiscovery: true,
        supportsCorroboration: true,
        role: "secondary",
        updateFrequency: "several/week",
        licensingNotes: "Company/community blog; attribute Hugging Face; not a wire.",
        notes: "Phase 4: AI specialty secondary for evergreen Blog + AI desk pairing.",
    },

    // ── Discovery-only (active) ─────────────────────────────────────────────
    {
        id: "arxiv-cs-ai",
        name: "arXiv cs.AI",
        organization: "arXiv / Cornell",
        domain: "arxiv.org",
        type: "rss",
        scope: ["international"],
        topics: ["ai", "research", "software"],
        coverageType: "preprint",
        geography: "international",
        homepage: "https://arxiv.org/list/cs.AI/recent",
        feedUrl: "https://rss.arxiv.org/rss/cs.AI",
        authorityTier: SOURCE_TIERS.TIER_3_DISCOVERY_ONLY,
        requiresSecondaryConfirmation: true,
        active: true,
        supportsDiscovery: true,
        supportsCorroboration: false,
        role: "discovery",
        updateFrequency: "daily",
        licensingNotes: "Preprint metadata; papers are not independent validation of their own claims.",
        notes: "Phase 2: reclassified discovery-only. High volume previously skewed clusters without corroboration value.",
    },

    // ── Documented unavailable / licensed / inactive ────────────────────────
    {
        id: "ap-wire",
        name: "Associated Press",
        organization: "Associated Press",
        domain: "apnews.com",
        type: "manual",
        scope: ["national", "international"],
        topics: ["technology", "policy", "science", "business", "finance"],
        coverageType: "wire",
        geography: "US / international",
        homepage: "https://apnews.com/",
        feedUrl: null,
        authorityTier: SOURCE_TIERS.TIER_1_NEWS,
        requiresSecondaryConfirmation: true,
        active: false,
        supportsDiscovery: false,
        supportsCorroboration: false,
        role: "secondary",
        updateFrequency: "continuous",
        licensingNotes: "Licensed wire — configure verified licensed endpoint; do not scrape.",
        notes: "UNAVAILABLE without license. Documented for future activation.",
    },
    {
        id: "reuters-wire",
        name: "Reuters",
        organization: "Reuters",
        domain: "reuters.com",
        type: "manual",
        scope: ["national", "international"],
        topics: ["technology", "finance", "policy", "business"],
        coverageType: "wire",
        geography: "international",
        homepage: "https://www.reuters.com/",
        feedUrl: null,
        authorityTier: SOURCE_TIERS.TIER_1_NEWS,
        requiresSecondaryConfirmation: true,
        active: false,
        supportsDiscovery: false,
        supportsCorroboration: false,
        role: "secondary",
        updateFrequency: "continuous",
        licensingNotes: "Licensed wire — configure verified licensed endpoint; do not scrape.",
        notes: "UNAVAILABLE without license.",
    },
    {
        id: "bloomberg",
        name: "Bloomberg",
        organization: "Bloomberg",
        domain: "bloomberg.com",
        type: "manual",
        scope: ["national", "international"],
        topics: ["finance", "business", "technology"],
        coverageType: "newsroom",
        geography: "international",
        homepage: "https://www.bloomberg.com/",
        feedUrl: null,
        authorityTier: SOURCE_TIERS.TIER_1_NEWS,
        requiresSecondaryConfirmation: true,
        active: false,
        supportsDiscovery: false,
        supportsCorroboration: false,
        role: "secondary",
        updateFrequency: "continuous",
        licensingNotes: "Paywalled / licensed — no public ingest path configured.",
        notes: "UNAVAILABLE — documented rather than forced.",
    },
    {
        id: "financial-times",
        name: "Financial Times",
        organization: "Financial Times",
        domain: "ft.com",
        type: "manual",
        scope: ["international"],
        topics: ["finance", "business", "technology"],
        coverageType: "newsroom",
        geography: "international",
        homepage: "https://www.ft.com/",
        feedUrl: null,
        authorityTier: SOURCE_TIERS.TIER_1_NEWS,
        requiresSecondaryConfirmation: true,
        active: false,
        supportsDiscovery: false,
        supportsCorroboration: false,
        role: "secondary",
        updateFrequency: "continuous",
        licensingNotes: "Paywalled / licensed — no public ingest path configured.",
        notes: "UNAVAILABLE — documented rather than forced.",
    },
    {
        id: "cnbc",
        name: "CNBC",
        organization: "CNBC",
        domain: "cnbc.com",
        type: "manual",
        scope: ["national", "international"],
        topics: ["finance", "business", "technology"],
        coverageType: "newsroom",
        geography: "US / international",
        homepage: "https://www.cnbc.com/",
        feedUrl: null,
        authorityTier: SOURCE_TIERS.TIER_1_NEWS,
        requiresSecondaryConfirmation: true,
        active: false,
        supportsDiscovery: false,
        supportsCorroboration: false,
        role: "secondary",
        updateFrequency: "continuous",
        licensingNotes: "No verified CinNova-safe public feed configured yet.",
        notes: "UNAVAILABLE pending verified feed/terms review.",
    },
    {
        id: "wired",
        name: "Wired",
        organization: "Condé Nast / Wired",
        domain: "wired.com",
        type: "manual",
        scope: ["national", "international"],
        topics: ["technology", "ai", "science"],
        coverageType: "specialty-news",
        geography: "US / international",
        homepage: "https://www.wired.com/",
        feedUrl: null,
        authorityTier: SOURCE_TIERS.TIER_2_REPUTABLE,
        requiresSecondaryConfirmation: true,
        active: false,
        supportsDiscovery: false,
        supportsCorroboration: false,
        role: "secondary",
        updateFrequency: "daily",
        licensingNotes: "No verified CinNova-safe public feed configured yet.",
        notes: "UNAVAILABLE pending verified feed/terms review.",
    },
    {
        id: "science-journal",
        name: "Science (AAAS)",
        organization: "American Association for the Advancement of Science",
        domain: "science.org",
        type: "manual",
        scope: ["international"],
        topics: ["science", "health", "environment"],
        coverageType: "journal",
        geography: "international",
        homepage: "https://www.science.org/",
        feedUrl: null,
        authorityTier: SOURCE_TIERS.TIER_2_REPUTABLE,
        requiresSecondaryConfirmation: true,
        active: false,
        supportsDiscovery: false,
        supportsCorroboration: false,
        role: "secondary",
        updateFrequency: "weekly",
        licensingNotes: "Paywalled journal — no free bulk ingest configured.",
        notes: "UNAVAILABLE — documented rather than forced.",
    },
    {
        id: "anthropic-news",
        name: "Anthropic News",
        organization: "Anthropic",
        domain: "anthropic.com",
        type: "manual",
        scope: ["national", "international"],
        topics: ["ai", "technology", "policy"],
        coverageType: "company-newsroom",
        geography: "US / international",
        homepage: "https://www.anthropic.com/news",
        feedUrl: null,
        authorityTier: SOURCE_TIERS.TIER_1_PRIMARY,
        requiresSecondaryConfirmation: true,
        active: false,
        supportsDiscovery: false,
        supportsCorroboration: false,
        role: "primary",
        updateFrequency: "irregular",
        licensingNotes: "No public RSS found (404 on /news/rss).",
        notes: "UNAVAILABLE — no verified public feed.",
    },
    {
        id: "nih-news",
        name: "NIH News Releases",
        organization: "National Institutes of Health",
        domain: "nih.gov",
        type: "official",
        scope: ["national"],
        topics: ["health", "science"],
        coverageType: "official-press",
        geography: "US",
        homepage: "https://www.nih.gov/news-events/news-releases",
        feedUrl: null,
        authorityTier: SOURCE_TIERS.TIER_1_PRIMARY,
        requiresSecondaryConfirmation: false,
        active: false,
        supportsDiscovery: false,
        supportsCorroboration: false,
        role: "primary",
        updateFrequency: "several/week",
        licensingNotes: "Feed endpoints returned 403; do not scrape HTML.",
        notes: "UNAVAILABLE — HTTP 403 on probed RSS endpoints.",
    },
    {
        id: "white-house-briefing",
        name: "White House Briefing Room",
        organization: "The White House",
        domain: "whitehouse.gov",
        type: "official",
        scope: ["national", "international"],
        topics: ["policy", "ai", "infrastructure"],
        coverageType: "official-press",
        geography: "US",
        homepage: "https://www.whitehouse.gov/briefing-room/",
        feedUrl: null,
        authorityTier: SOURCE_TIERS.TIER_1_PRIMARY,
        requiresSecondaryConfirmation: false,
        active: false,
        supportsDiscovery: false,
        supportsCorroboration: false,
        role: "primary",
        updateFrequency: "daily",
        licensingNotes: "Configure a verified current official endpoint before enabling.",
        notes: "Inactive pending verified feed.",
    },
    {
        id: "doj-press",
        name: "DOJ Justice News",
        organization: "U.S. Department of Justice",
        domain: "justice.gov",
        type: "manual",
        scope: ["national"],
        topics: ["policy", "regulation", "cybersecurity", "business"],
        coverageType: "official-press",
        geography: "US",
        homepage: "https://www.justice.gov/news",
        feedUrl: null,
        authorityTier: SOURCE_TIERS.TIER_1_PRIMARY,
        requiresSecondaryConfirmation: false,
        active: false,
        supportsDiscovery: false,
        supportsCorroboration: false,
        role: "primary",
        updateFrequency: "several/week",
        licensingNotes: "No verified CinNova-safe public feed configured yet.",
        notes: "UNAVAILABLE pending verified endpoint.",
    },
    {
        id: "local-partner",
        name: "Verified Local News Partner",
        organization: "(unconfigured)",
        domain: "",
        type: "manual",
        scope: ["local", "state"],
        topics: ["infrastructure", "education", "real estate", "policy"],
        coverageType: "partner",
        geography: "local/state",
        homepage: "",
        feedUrl: null,
        authorityTier: SOURCE_TIERS.TIER_1_NEWS,
        requiresSecondaryConfirmation: true,
        active: false,
        supportsDiscovery: false,
        supportsCorroboration: false,
        role: "secondary",
        updateFrequency: "unknown",
        licensingNotes: "Configure verified publisher and endpoint before enabling.",
        notes: "Placeholder — no local/state partner configured.",
    },
    {
        id: "hacker-news-discovery",
        name: "Hacker News Discovery",
        organization: "Y Combinator",
        domain: "news.ycombinator.com",
        type: "manual",
        scope: ["international"],
        topics: ["software", "ai", "cybersecurity"],
        coverageType: "community",
        geography: "international",
        homepage: "https://news.ycombinator.com/",
        feedUrl: null,
        authorityTier: SOURCE_TIERS.TIER_3_DISCOVERY_ONLY,
        requiresSecondaryConfirmation: true,
        active: false,
        supportsDiscovery: true,
        supportsCorroboration: false,
        role: "discovery",
        updateFrequency: "continuous",
        licensingNotes: "Community discussion — discovery only.",
        notes: "Discovery only. Cannot support READY or corroboration by itself.",
    },
    {
        id: "community-tip",
        name: "Community Tip Queue",
        organization: "CinNova",
        domain: "getcinnova.com",
        type: "manual",
        scope: ["local", "state"],
        topics: ["technology", "education", "infrastructure"],
        coverageType: "community",
        geography: "local/state",
        homepage: "https://getcinnova.com/news",
        feedUrl: null,
        authorityTier: SOURCE_TIERS.TIER_3_DISCOVERY_ONLY,
        requiresSecondaryConfirmation: true,
        active: false,
        supportsDiscovery: true,
        supportsCorroboration: false,
        role: "discovery",
        updateFrequency: "irregular",
        licensingNotes: "Internal tip queue.",
        notes: "Discovery only. Every claim requires verification from independent reputable sources.",
    },
    {
        id: "blocked-seo-farms",
        name: "Blocked SEO / rumor farms (policy slot)",
        organization: "n/a",
        domain: "",
        type: "blocked",
        scope: [],
        topics: [],
        coverageType: "blocked",
        geography: "n/a",
        homepage: "",
        feedUrl: null,
        authorityTier: SOURCE_TIERS.BLOCKED,
        requiresSecondaryConfirmation: true,
        active: false,
        supportsDiscovery: false,
        supportsCorroboration: false,
        role: "blocked",
        updateFrequency: "n/a",
        licensingNotes: "Never ingest affiliate farms, rumor blogs, or unverifiable scrapes.",
        notes: "BLOCKED policy placeholder — untrusted content classes.",
    },
];

/** Legacy alias retained for older code expecting TIER_4_* discovery entries. */
export const LEGACY_TIER_4_DISCOVERY_IDS = ["arxiv-cs-ai", "hacker-news-discovery", "community-tip"];

export function getActiveSources() {
    return SOURCE_REGISTRY.filter(
        (source) =>
            source.active
            && source.feedUrl
            && source.authorityTier !== SOURCE_TIERS.BLOCKED
            && source.type !== "blocked",
    );
}

export function getSourceById(id) {
    return SOURCE_REGISTRY.find((source) => source.id === id) || null;
}

export function listRegistryAuditRows() {
    return SOURCE_REGISTRY.map((source) => ({
        id: source.id,
        organization: source.organization,
        domain: source.domain,
        deskTopics: source.topics,
        coverageType: source.coverageType,
        authorityTier: source.authorityTier,
        feedType: source.type,
        geography: source.geography,
        updateFrequency: source.updateFrequency,
        active: source.active,
        supportsDiscovery: source.supportsDiscovery,
        supportsCorroboration: source.supportsCorroboration,
        role: source.role,
        licensingNotes: source.licensingNotes,
        feedUrl: source.feedUrl,
        notes: source.notes,
    }));
}
