export const SOURCE_REGISTRY = [
    {
        id: "nist-news",
        name: "NIST News",
        type: "rss",
        scope: ["national"],
        topics: ["ai", "cybersecurity", "standards", "semiconductors"],
        homepage: "https://www.nist.gov/news-events/news",
        feedUrl: "https://www.nist.gov/news-events/news/rss.xml",
        authorityTier: "TIER_1_PRIMARY",
        requiresSecondaryConfirmation: false,
        active: true,
        notes: "Official NIST news feed.",
    },
    {
        id: "cisa-advisories",
        name: "CISA Cybersecurity Advisories",
        type: "rss",
        scope: ["national"],
        topics: ["cybersecurity", "infrastructure", "software"],
        homepage: "https://www.cisa.gov/news-events/cybersecurity-advisories",
        feedUrl: "https://www.cisa.gov/cybersecurity-advisories/all.xml",
        authorityTier: "TIER_1_PRIMARY",
        requiresSecondaryConfirmation: false,
        active: true,
        notes: "Official CISA advisory feed.",
    },
    {
        id: "nasa-press",
        name: "NASA Press Releases",
        type: "rss",
        scope: ["national", "international"],
        topics: ["science", "space", "technology"],
        homepage: "https://www.nasa.gov/news-release/",
        feedUrl: "https://www.nasa.gov/rss/dyn/press_release.rss",
        authorityTier: "TIER_1_PRIMARY",
        requiresSecondaryConfirmation: false,
        active: true,
        notes: "Official NASA press-release feed.",
    },
    {
        id: "sec-press",
        name: "SEC Press Releases",
        type: "rss",
        scope: ["national"],
        topics: ["finance", "regulation", "technology"],
        homepage: "https://www.sec.gov/newsroom/press-releases",
        feedUrl: "https://www.sec.gov/news/pressreleases.rss",
        authorityTier: "TIER_1_PRIMARY",
        requiresSecondaryConfirmation: false,
        active: true,
        notes: "Official SEC press-release feed. Live requests must identify the application per SEC policy.",
    },
    {
        id: "ftc-news",
        name: "FTC News and Events",
        type: "official",
        scope: ["national"],
        topics: ["consumer tech", "policy", "regulation", "privacy"],
        homepage: "https://www.ftc.gov/news-events",
        feedUrl: null,
        authorityTier: "TIER_1_PRIMARY",
        requiresSecondaryConfirmation: false,
        active: false,
        notes: "Configure a verified current FTC endpoint before enabling; no endpoint is assumed.",
    },
    {
        id: "nsf-news",
        name: "NSF News",
        type: "official",
        scope: ["national"],
        topics: ["science", "ai", "education", "research"],
        homepage: "https://new.nsf.gov/news",
        feedUrl: null,
        authorityTier: "TIER_1_PRIMARY",
        requiresSecondaryConfirmation: false,
        active: false,
        notes: "Configure a verified current NSF endpoint before enabling.",
    },
    {
        id: "ap-wire",
        name: "Associated Press",
        type: "manual",
        scope: ["national", "international"],
        topics: ["technology", "policy", "science"],
        homepage: "https://apnews.com/",
        feedUrl: null,
        authorityTier: "TIER_2_HIGH_AUTHORITY",
        requiresSecondaryConfirmation: true,
        active: false,
        notes: "Configure verified licensed endpoint; do not scrape.",
    },
    {
        id: "reuters-wire",
        name: "Reuters",
        type: "manual",
        scope: ["national", "international"],
        topics: ["technology", "finance", "policy"],
        homepage: "https://www.reuters.com/",
        feedUrl: null,
        authorityTier: "TIER_2_HIGH_AUTHORITY",
        requiresSecondaryConfirmation: true,
        active: false,
        notes: "Configure verified licensed endpoint; do not scrape.",
    },
    {
        id: "local-partner",
        name: "Verified Local News Partner",
        type: "manual",
        scope: ["local", "state"],
        topics: ["infrastructure", "education", "real estate", "policy"],
        homepage: "",
        feedUrl: null,
        authorityTier: "TIER_2_HIGH_AUTHORITY",
        requiresSecondaryConfirmation: true,
        active: false,
        notes: "Placeholder registry slot; configure verified publisher and endpoint before enabling.",
    },
    {
        id: "mit-ai",
        name: "MIT News: Artificial Intelligence",
        type: "rss",
        scope: ["national", "international"],
        topics: ["ai", "research", "education"],
        homepage: "https://news.mit.edu/topic/artificial-intelligence2",
        feedUrl: "https://news.mit.edu/rss/topic/artificial-intelligence2",
        authorityTier: "TIER_3_REPUTABLE_SECONDARY",
        requiresSecondaryConfirmation: true,
        active: true,
        notes: "MIT News topical feed; corroborate external claims.",
    },
    {
        id: "arxiv-cs-ai",
        name: "arXiv cs.AI",
        type: "rss",
        scope: ["international"],
        topics: ["ai", "research", "software"],
        homepage: "https://arxiv.org/list/cs.AI/recent",
        feedUrl: "https://rss.arxiv.org/rss/cs.AI",
        authorityTier: "TIER_3_REPUTABLE_SECONDARY",
        requiresSecondaryConfirmation: true,
        active: true,
        notes: "Research discovery feed; papers are not independent validation of their own claims.",
    },
    {
        id: "white-house-briefing",
        name: "White House Briefing Room",
        type: "official",
        scope: ["national", "international"],
        topics: ["policy", "ai", "infrastructure"],
        homepage: "https://www.whitehouse.gov/briefing-room/",
        feedUrl: null,
        authorityTier: "TIER_1_PRIMARY",
        requiresSecondaryConfirmation: false,
        active: false,
        notes: "Configure a verified current official endpoint before enabling.",
    },
    {
        id: "hacker-news-discovery",
        name: "Hacker News Discovery",
        type: "manual",
        scope: ["international"],
        topics: ["software", "ai", "cybersecurity"],
        homepage: "https://news.ycombinator.com/",
        feedUrl: null,
        authorityTier: "TIER_4_DISCOVERY_ONLY",
        requiresSecondaryConfirmation: true,
        active: false,
        notes: "Discovery only. Cannot support READY or corroboration by itself.",
    },
    {
        id: "community-tip",
        name: "Community Tip Queue",
        type: "manual",
        scope: ["local", "state"],
        topics: ["technology", "education", "infrastructure"],
        homepage: "https://getcinnova.com/news",
        feedUrl: null,
        authorityTier: "TIER_4_DISCOVERY_ONLY",
        requiresSecondaryConfirmation: true,
        active: false,
        notes: "Discovery only. Every claim requires verification from independent reputable sources.",
    },
];

export function getActiveSources() {
    return SOURCE_REGISTRY.filter((source) => source.active && source.feedUrl);
}

export function getSourceById(id) {
    return SOURCE_REGISTRY.find((source) => source.id === id) || null;
}
